
@host = http://localhost:3000
@api = {{host}}/api
@password = 1234567890

###

# @name andrew
POST {{api}}/users/new
Content-Type: application/json

{
    "name": "Andrew",
    "email": "andrew@test.me",
    "password": "{{password}}",
    "birthday": "{{$datetime iso8601 -32 y}}"
}

###

@user_id = {{andrew.response.body.$.user_id}}

# @name yep
GET {{api}}/users/{{user_id}} HTTP/1.1
Authorization: Basic andrew {{password}}

###

GET {{api}}/search
    ?keyword=andrew
    &filter=birthday
Authorization: Basic andrew {{password}}
